### ISSUE TITLE
Prettiest Payoff

### ISSUE THREAD

**Issue by jlthibault** [theadamparker/BusFed-2014#73]
Prettiest Payoff
Votes cast isn’t compelling
Bus actually drives in a direction? Bus bar graph?
Convey that these are apples to apples—the counties are the same size.
Add words about “montana’s four largest counties” or something like that.
2 feasible ways to make it move
GIF with a long delay at the end
SVG
Add county after these names

**Comment by jlthibault** [comment]
@theadamparker I've added in the images and gifs here (with text changes etc) but in the process...
- nice comfy spaces between graphics disappeared. What's the best way to add image top/bottom margins when the image is inside a column structure template like this? Because of the template, I'd be afraid it would add that margin to all images in the page.
- it looks like maybe some h4 text styles were changed?  

Is this the approach you want to go with for animations? Know we had talked about svg's, but maybe you had another thing in mind?

**Comment by theadamparker** [comment]
@jlthibault 

> nice comfy spaces between graphics disappeared. What's the best way to add image top/bottom margins when the image is inside a column structure template like this? Because of the template, I'd be afraid it would add that margin to all images in the page.

I'll add a selector for this and add some more space. And I'll tag you when I'm done.

> it looks like maybe some h4 text styles were changed?

They were changed in [this commit](https://github.com/theadamparker/BusFed-2014/commit/a0c36eb1acb959ebdc60649f27a32b8904ddef71)—you accidentally used `<h4-graphic>` tags instead of `<h4 class="graphic">`. I didn't revise the style for them, just noticed the error and relinked. I'm not sure what exactly you had in mind for captions.
